# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# See https://github.com/pre-commit/pre-commit-hooks
repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-ast
  - id: check-added-large-files
  - id: check-yaml
    args: [--unsafe]
  - id: check-toml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args: [--remove]
  - id: name-tests-test
    args: [--pytest-test-first]
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli

- repo: local
  hooks:
  - id: lint
    name: lint
    entry: make lint
    types: [python]
    language: system
    pass_filenames: false

  - id: audit
    name: audit
    entry: make audit
    types: [python]
    language: system
    pass_filenames: false

- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.12.0
  hooks:
    - id: commitizen
