name: ci

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12, 3.13]

    steps:
    - name: Checkout codes
      uses: actions/checkout@v4.1.1

    - name: Setup python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64

    - name: Install dependencies
      run: pip install -e .[dev]

    - name: Run tests
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4.0.0-beta.3
