name: pre-commit

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codes
      uses: actions/checkout@v4.1.7

    - name: Setup python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: 3.8
        architecture: x64

    - name: Install dependencies
      run: make install

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
